---
version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
    networks:
      - app-network
  spinner:
    build: .
    ports: 
      - '3000:3000'
    depends_on:
      - cache
    networks:
      - app-network
volumes:
  cache:
    driver: local